### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by SteffenPL** [SteffenPL/MyPaintEdSlides#5]
This issue is to collect ideas on how this script could be extended:

### Usability
- [ ] as @lenalebt suggested: installation as a python package?
- [ ] slim config/project file s.t. `python ora_interace.py <input_folder>` is sufficient?
- [ ] integration into MyPaint? (MyPaint uses python, however, Krita is maybe better for some people.)

However, a python script will always restrict the usage to people who know how to run a python script.

- [ ] **Should we use React.js instead of python?** We could load an ORA file and directly generate the HTML via react.js. This would allow using the presentations without any prior installation!

Are there other frameworks which would allow usage of the script without installation/compilation?

### Features

- [ ] More keywords like
  - [ ] `(delete: <previous slide name>)`  [deletes a layer for all further generated slides]
  - [ ] `(no slide)` [skips the generation of an slide but displays the layer for further slides]
  - [ ] ...more ideas?
- [ ] Is there a better syntax for keywords?
- [ ] How to include videos
- [ ] Replacing the slow `src-over` with some efficient library call or pushing the image overlay to the HTML side?

### Good practices
- [ ] As always: tests would be good.
